# Generated by Django 3.0.5 on 2021-09-30 03:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('msg', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodobj', models.CharField(max_length=40)),
                ('qnt', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('total', models.FloatField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodobj', models.CharField(max_length=40)),
                ('qnt', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('total', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group_name', models.CharField(max_length=30)),
                ('display_product', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=100)),
                ('product_name', models.CharField(max_length=30, unique=True)),
                ('regular_price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_last_date', models.DateField()),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('product_img2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('product_img3', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date', models.DateField(default=datetime.datetime(2021, 9, 30, 3, 47, 1, 638302, tzinfo=utc))),
                ('product_desc', models.TextField(blank=True, max_length=200, null=True)),
                ('product_belongs', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('band', 'Band')], max_length=100)),
                ('featured_product', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=100, null=True)),
                ('display_on_women_section', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=100, null=True)),
                ('display_on_men_section', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=100, null=True)),
                ('display_on_offer_section', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WatchApp.Brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WatchApp.Color')),
                ('size', models.ForeignKey(default=88, on_delete=django.db.models.deletion.CASCADE, to='WatchApp.Size')),
            ],
            options={
                'unique_together': {('product_group_name', 'color')},
            },
        ),
    ]
