# Generated by Django 3.0.5 on 2021-09-30 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WatchApp', '0002_auto_20210930_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(default='pink', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 30, 5, 7, 47, 348027, tzinfo=utc)),
        ),
    ]
